### ISSUE TITLE
Feedback: Faction drop-down Allows selections of factions not in era

### ISSUE THREAD

**Issue by OftKilted** [free-worlds-tech/free-worlds-tech.github.io#54]
While not a “game breaker” if one has selected an Era, then it would be helpful to not allow selection of factions that don’t exist in a particular era.

e.g. Clan Nova Cat in ilClan, or Wolf Empire prior to ilClan. Making factions unavailable for selection in the drop-down or to flag as “not in era” would be beneficial.

Terminal’s Tech Tools (for Alpha Strike) would be a good example of the functionality: 

https://github.com/jsc17/Terminals-BT

When an era is selected it filters out unavailable factions for that era. (It also provides the General lists for perusal.)

**Comment by scottboehmer** [comment]
I implemented filtering of the lists with https://github.com/free-worlds-tech/free-worlds-tech.github.io/pull/58
